### PR TITLE
DHT22 _celsius was wrong

### PR DESCRIPTION
**Pull request by Ehsan-Shahnazi**

### CODE REVIEW

**Comment by offcircuit** [comment]
Hi,

Can you be more explicit.

Thanks,
Helder Rodrigues

**Comment by offcircuit** [comment]
Yes, the calculation was wrong.

Thanks,
Did you find anything else?

Thanks,
Helder Rodrigues

**Comment by Ehsan-Shahnazi** [comment]
hello
how can use DHT22 without library... i want to use Attiny13 (1Kb).it has low ram and i cant use lib.

**Comment by offcircuit** [comment]
Hello,

I dont try with the attiny.
try this links

https://github.com/jscrane/DHT/blob/master/DHT.cpp
https://weekly-geekly.github.io/articles/371973/index.html

Helder Rodrigues

**Comment by Ehsan-Shahnazi** [comment]
hi
if you want write code for run dht22 on Arduino uno without any library, how write it?
can you write here. just get temp and humidity.
Eshahnazi@gmail.com
thank you

**Comment by Ehsan-Shahnazi** [comment]
i write this code...but should be reduce 478 byte. yet is 1478 Byte .


```
#define pin A2
#define PinPotTemp A1
#define PinPotHum A3
#define OutTemp 2
#define OutHum 3
#define SDHT_CYCLES microsecondsToClockCycles(200)

int PotTemp;
int PotHum;

void setup() {
  
   pinMode(OutTemp, OUTPUT); // Pin2 = A3
  pinMode(OutHum, OUTPUT); // Pin7 = A1

}

void loop() {
  // put your main code here, to run repeatedly:
  
      uint8_t data[5] = {0, 0, 0, 0, 0};
      pinMode(pin, OUTPUT);
      digitalWrite(pin, LOW);
      pulseIn(pin, HIGH, 1000);
      digitalWrite(pin, HIGH);
      pinMode(pin, INPUT);

      if (!pulseIn(pin, HIGH, 300)) return false;
      for (uint8_t i = 0; i < 40; i++) data[i / 8] += data[i / 8] + (pulse( LOW) > pulse( HIGH));

//      if (data[4] != uint8_t(data[0] + data[1] + data[2] + data[3])) return false;
      
     int humidity = (uint16_t(data[0] << 8) | data[1]) * .1;
     int celsius = (uint16_t((data[2] & 0x7F)<< 8) + data[3]) * ((data[2] & 0x80) ? -.1 : .1);

  PotTemp= analogRead(PinPotTemp);
  PotTemp = map(PotTemp, 0, 1023, 0, 80); // temp 0-80
  if (PotTemp < celsius)digitalWrite(OutTemp, HIGH);
  if (PotTemp > celsius)digitalWrite(OutTemp, LOW);
  
  PotHum= analogRead(PinPotHum);
  PotHum = map(PotHum, 0, 1023, 0, 100); // Hum 0-100
  if (PotHum < humidity)digitalWrite(OutHum, HIGH);
  if (PotHum > humidity)digitalWrite(OutHum, LOW);
  
//  delay(2000);
 
}

     uint16_t pulse( bool state) 
    {
    uint16_t cycle = SDHT_CYCLES;
    while ((digitalRead(pin) == state) && cycle--);
    return cycle;
    }
```

**Comment by Ehsan-Shahnazi** [comment]
[https://github.com/jscrane/DHT/blob/master/DHT.cpp](url)
i test it, but had some error, after Fix Errors and add a few line code, Sketch uses 1742 bytes. 742 byte most be reduce.!!!???

**Comment by Ehsan-Shahnazi** [comment]
> i write this code...but should be reduce 478 byte. yet is 1478 Byte .
> 
> ```
> #define pin A2
> #define PinPotTemp A1
> #define PinPotHum A3
> #define OutTemp 2
> #define OutHum 3
> #define SDHT_CYCLES microsecondsToClockCycles(200)
> 
> int PotTemp;
> int PotHum;
> 
> void setup() {
>   
>    pinMode(OutTemp, OUTPUT); // Pin2 = A3
>   pinMode(OutHum, OUTPUT); // Pin7 = A1
> 
> }
> 
> void loop() {
>   // put your main code here, to run repeatedly:
>   
>       uint8_t data[5] = {0, 0, 0, 0, 0};
>       pinMode(pin, OUTPUT);
>       digitalWrite(pin, LOW);
>       pulseIn(pin, HIGH, 1000);
>       digitalWrite(pin, HIGH);
>       pinMode(pin, INPUT);
> 
>       if (!pulseIn(pin, HIGH, 300)) return false;
>       for (uint8_t i = 0; i < 40; i++) data[i / 8] += data[i / 8] + (pulse( LOW) > pulse( HIGH));
> 
> //      if (data[4] != uint8_t(data[0] + data[1] + data[2] + data[3])) return false;
>       
>      int humidity = (uint16_t(data[0] << 8) | data[1]) * .1;
>      int celsius = (uint16_t((data[2] & 0x7F)<< 8) + data[3]) * ((data[2] & 0x80) ? -.1 : .1);
> 
>   PotTemp= analogRead(PinPotTemp);
>   PotTemp = map(PotTemp, 0, 1023, 0, 80); // temp 0-80
>   if (PotTemp < celsius)digitalWrite(OutTemp, HIGH);
>   if (PotTemp > celsius)digitalWrite(OutTemp, LOW);
>   
>   PotHum= analogRead(PinPotHum);
>   PotHum = map(PotHum, 0, 1023, 0, 100); // Hum 0-100
>   if (PotHum < humidity)digitalWrite(OutHum, HIGH);
>   if (PotHum > humidity)digitalWrite(OutHum, LOW);
>   
> //  delay(2000);
>  
> }
> 
>      uint16_t pulse( bool state) 
>     {
>     uint16_t cycle = SDHT_CYCLES;
>     while ((digitalRead(pin) == state) && cycle--);
>     return cycle;
>     }
> ```

if you Optimize this code. I can run it on Attiny13.
very thanks

**Comment by offcircuit** [comment]
Hi again,

Try this:

#define pin A2
#define PinPotTemp A1
#define PinPotHum A3
#define OutTemp 2
#define OutHum 3
int PotTemp;
int PotHum;

void setup() {
  pinMode(OutTemp, OUTPUT); // Pin2 = A3
  pinMode(OutHum, OUTPUT); // Pin7 = A1
}

void loop() {
  // put your main code here, to run repeatedly:

  uint8_t data[5] = {0, 0, 0, 0, 0};
  pinMode(pin, OUTPUT);
  digitalWrite(pin, LOW);
  pulseIn(pin, HIGH, 1000);
  digitalWrite(pin, HIGH);
  pinMode(pin, INPUT);

  if (pulseIn(pin, HIGH, 300)) {
    for (uint8_t i = 0; i < 40; i++) data[i / 8] += data[i / 8] + (pulse( LOW) > pulse( HIGH));

    if (data[4] == uint8_t(data[0] + data[1] + data[2] + data[3])) {

      digitalWrite(OutTemp, map(analogRead(PinPotTemp), 0, 1023, 0, 800) < (uint16_t((data[2] & 0x7F) << 8) + data[3]));
      digitalWrite(OutHum, map(analogRead(PinPotHum), 0, 1023, 0, 1000) < (uint16_t(data[0] << 8) | data[1]));

    }
  }
  delay(2000);
}

uint16_t pulse( bool state)
{
  uint16_t cycle = microsecondsToClockCycles(200);
  while ((digitalRead(pin) == state) && cycle--);
  return cycle;
}

Helder Rodrigues

**Comment by Ehsan-Shahnazi** [comment]
Hi
Its ok. But for -temp, What should i do?

https://github.com/jscrane/DHT/blob/master/DHT.cpp
I try run  this lib,It also displays a negative temperature.
If you Optimize code, that it also measures the negative temperature.so your code is  Lighter. Because in that lib use Micro & Milis function.

**Comment by offcircuit** [comment]
Hi,

I dont know if what you need:

`#define pin A2
#define PinPotTemp A1
#define PinPotHum A3
#define OutTemp 2
#define OutHum 3
#define DHT_CYCLES microsecondsToClockCycles(200);

void setup() {
  pinMode(OutTemp, OUTPUT);
  pinMode(OutHum, OUTPUT);
}

void loop() {
  uint8_t data[5] = {0, 0, 0, 0, 0};

  pinMode(pin, OUTPUT);
  digitalWrite(pin, LOW);
  pulseIn(pin, HIGH, 1000);
  digitalWrite(pin, HIGH);
  pinMode(pin, INPUT);

  if (pulseIn(pin, HIGH, 300)) {

    for (uint8_t i = 0; i < 40; i++) data[i / 8] += data[i / 8] + (pulse(LOW) > pulse(HIGH));

    if (data[4] == uint8_t(data[0] + data[1] + data[2] + data[3])) {

      int16_t celsius = (uint16_t((data[2] & 0x7F) << 8) | data[3]) * ((data[2] & 0x80) ? -1 : 1);
      uint16_t humidity = (uint16_t(data[0] << 8) | data[1]);

      digitalWrite(OutTemp, map(analogRead(PinPotTemp), 0, 1023, -400, 800) < celsius);
      digitalWrite(OutHum, map(analogRead(PinPotHum), 0, 1023, 0, 1000) < humidity);
    }
  }
  delay(2000);
}

uint16_t pulse( bool state)
{
  uint16_t cycle = DHT_CYCLES;
  while ((digitalRead(pin) == state) && cycle--);
  return cycle;
}
`

Helder Rodrigues

**Comment by Ehsan-Shahnazi** [comment]
Hi
i want control temp and hum with tolerance Z.
for sample:
Pot Temp=25 C , z=1
 if temp higher than 26 C ==>> OutTemp, HIGH
 if temp lower than 24 C ==>> OutTemp, LOW

```
int z =10;
..... 
   PotTemp= analogRead(PinPotTemp);
  PotTemp = map(PotTemp, 0, 1023, -400, 800); // temp -40 : 80
  if (PotTemp+z < (dht.getTemperature()) )digitalWrite(OutTemp, HIGH);
  if (PotTemp-z > (dht.getTemperature()) )digitalWrite(OutTemp, LOW);
  
  PotHum= analogRead(PinPotHum);
  PotHum = map(PotHum, 0, 1023, 0, 1000); // Hum 0 : 100
  if (PotHum+z < (dht.getHumidity()))digitalWrite(OutHum, HIGH);
  if (PotHum-z > (dht.getHumidity()))digitalWrite(OutHum, LOW);
```

**Comment by offcircuit** [comment]
Hello,

How about this:

866 bytes (84%) / 1024 bytes
5 bytes (7%) / 64 bytes

`#define pin A2
#define PinPotTemp A1
#define PinPotHum A3
#define OutTemp 2
#define OutHum 3
#define DHT_CYCLES microsecondsToClockCycles(200)
#define TOLERANCE_CELSIUS 10
#define TOLERANCE_HUMIDITY 10

void setup() {
  pinMode(OutTemp, OUTPUT);
  pinMode(OutHum, OUTPUT);
}

void loop() {
  uint8_t data[5] = {0, 0, 0, 0, 0};

  pinMode(pin, OUTPUT);
  digitalWrite(pin, LOW);
  pulseIn(pin, HIGH, 1000);
  digitalWrite(pin, HIGH);
  pinMode(pin, INPUT);

  if (pulseIn(pin, HIGH, 300)) {

    for (uint8_t i = 0; i < 40; i++)
      data[i / 8] += data[i / 8] + (pulse(LOW) > pulse(HIGH));

    if (data[4] == uint8_t(data[0] + data[1] + data[2] + data[3])) {

      int16_t celsius = (uint16_t((data[2] & 0x7F) << 8) | data[3]) * ((data[2] & 0x80) ? -1 : 1);
      uint16_t humidity = (uint16_t(data[0] << 8) | data[1]);

      int16_t level = map(analogRead(PinPotTemp), 0, 1023, -400, 800);

      if ((level + TOLERANCE_CELSIUS) < celsius)
        digitalWrite(OutTemp, HIGH);
      else if ((level - TOLERANCE_CELSIUS) > celsius)
        digitalWrite(OutTemp, LOW);

      level = map(analogRead(PinPotHum), 0, 1023, 0, 1000);

      if ((level + TOLERANCE_HUMIDITY) < humidity)
        digitalWrite(OutHum, HIGH);
      else if ((level - TOLERANCE_HUMIDITY) > humidity)
        digitalWrite(OutHum, LOW);
    }
  }
  delay(2000);
}

uint16_t pulse( bool state)
{
  uint16_t cycle = DHT_CYCLES;
  while ((digitalRead(pin) == state) && cycle--);
  return cycle;
}`

Helder Rodrigues

**Comment by offcircuit** [comment]
Eu alterei a biblioteca para funcionar com o attiny,
mas agora os resultados são em decimos.
value 10 = 1,0º celsius.

Só esta disponivel na pagina
https://github.com/offcircuit/SDHT


Exprimente este codigo:


`
#include "SDHT.h"

SDHT dht;

#define pin A2
#define PinPotTemp A1
#define PinPotHum A3
#define OutTemp 2
#define OutHum 3

#define TOLERANCE_CELSIUS 10
#define TOLERANCE_HUMIDITY 10

void setup() {
  pinMode(OutTemp, OUTPUT);
  pinMode(OutHum, OUTPUT);
}

void loop() {

  if (dht.broadcast(DHT22, pin)) {

    int16_t level = map(analogRead(PinPotTemp), 0, 1023, -400, 800);

    if ((level + TOLERANCE_CELSIUS) < dht.celsius)
      digitalWrite(OutTemp, HIGH);
    else if ((level - TOLERANCE_CELSIUS) > dht.celsius)
      digitalWrite(OutTemp, LOW);

    level = map(analogRead(PinPotHum), 0, 1023, 0, 1000);

    if ((level + TOLERANCE_HUMIDITY) < dht.humidity)
      digitalWrite(OutHum, HIGH);
    else if ((level - TOLERANCE_HUMIDITY) > dht.humidity)
      digitalWrite(OutHum, LOW);

  }
  delay(2000);
}

`

Helder Rodrigues

**Comment by Ehsan-Shahnazi** [comment]
> 
> 
> Hello,
> 
> How about this:
> 
> 866 bytes (84%) / 1024 bytes
> 5 bytes (7%) / 64 bytes
> 
> `#define pin A2
> #define PinPotTemp A1
> #define PinPotHum A3
> #define OutTemp 2
> #define OutHum 3
> #define DHT_CYCLES microsecondsToClockCycles(200)
> #define TOLERANCE_CELSIUS 10
> #define TOLERANCE_HUMIDITY 10
> 
> void setup() {
> pinMode(OutTemp, OUTPUT);
> pinMode(OutHum, OUTPUT);
> }
> 
> void loop() {
> uint8_t data[5] = {0, 0, 0, 0, 0};
> 
> pinMode(pin, OUTPUT);
> digitalWrite(pin, LOW);
> pulseIn(pin, HIGH, 1000);
> digitalWrite(pin, HIGH);
> pinMode(pin, INPUT);
> 
> if (pulseIn(pin, HIGH, 300)) {
> 
> ```
> for (uint8_t i = 0; i < 40; i++)
>   data[i / 8] += data[i / 8] + (pulse(LOW) > pulse(HIGH));
> 
> if (data[4] == uint8_t(data[0] + data[1] + data[2] + data[3])) {
> 
>   int16_t celsius = (uint16_t((data[2] & 0x7F) << 8) | data[3]) * ((data[2] & 0x80) ? -1 : 1);
>   uint16_t humidity = (uint16_t(data[0] << 8) | data[1]);
> 
>   int16_t level = map(analogRead(PinPotTemp), 0, 1023, -400, 800);
> 
>   if ((level + TOLERANCE_CELSIUS) < celsius)
>     digitalWrite(OutTemp, HIGH);
>   else if ((level - TOLERANCE_CELSIUS) > celsius)
>     digitalWrite(OutTemp, LOW);
> 
>   level = map(analogRead(PinPotHum), 0, 1023, 0, 1000);
> 
>   if ((level + TOLERANCE_HUMIDITY) < humidity)
>     digitalWrite(OutHum, HIGH);
>   else if ((level - TOLERANCE_HUMIDITY) > humidity)
>     digitalWrite(OutHum, LOW);
> }
> ```
> 
> }
> delay(2000);
> }
> 
> uint16_t pulse( bool state)
> {
> uint16_t cycle = DHT_CYCLES;
> while ((digitalRead(pin) == state) && cycle--);
> return cycle;
> }`
> 
> Helder Rodrigues

**that's right...**

**Comment by Ehsan-Shahnazi** [comment]
> dht.humidity

**that's right...**
notic: if disable all function same as MILLIS and MICROS and other function in core_setting.h ( _C:\Users\Shahbaz\AppData\Local\Arduino15\packages\MicroCore\hardware\avr\1.0.4\cores\microcore_  AND   _C:\Users\Shahbaz\AppData\Local\Arduino15\packages\MicroCore\avr\cores\microcore_ ),
 sketch size reduce to 892 byte. if enable them may size up to 1kb.

**Comment by offcircuit** [comment]
Hi again,

The reduction was made by removing the "double" variable type.
I have previously tried using time functions, but it does not have the same permorance.

In my opinion now is better, but I do not know if all calculations are correct, because I did not find datasheets with examples.

Helder Rodrigues

**Comment by Ehsan-Shahnazi** [comment]
I compared the temperature and humidity with the sketch that uses (_https://github.com/jscrane/DHT/blob/master/DHT.cpp_) library. The results were the same. :) 👍

**Comment by offcircuit** [comment]
hi again,

are you saying something like this

<
#ifndef SDHT_H
#define SDHT_H

#define DHT11 0
#define DHT12 1
#define DHT21 2
#define DHT22 3

class SDHT
{
  private:
    uint16_t _humidity = 0;
    int16_t _celsius = 0;

  public:
    const uint16_t &humidity = _humidity;
    const int16_t &celsius = _celsius;

    explicit SDHT() {};

    bool broadcast(uint8_t model, uint8_t pin) {
      uint8_t data[5] = {0, 0, 0, 0, 0};

#ifdef ESP8266
      yield();
#endif

      pinMode(pin, OUTPUT);
      digitalWrite(pin, LOW);
      pulseIn(pin, HIGH, (model < DHT21) ? 20000 : 1000);
      digitalWrite(pin, HIGH);
      pinMode(pin, INPUT);

      if (pulseIn(pin, HIGH, 300)) {

        for (uint8_t i = 0; i < 40; i++)
          data[i / 8] += data[i / 8] + (pulse(pin, LOW) < pulse(pin, HIGH));

        if (data[4] == uint8_t(data[0] + data[1] + data[2] + data[3])) {

          switch (model) {
            case DHT11:
              _humidity = (data[0] * 10) + data[1];
              _celsius = (data[2] * 10) + data[3];
              break;

            case DHT12:
              _humidity = (data[0] * 10) + data[1];
              _celsius = ((data[2] * 10) + (data[3] & 0x7F)) * ((data[3] & 0x80) ? -1 : 1);
              break;

            case DHT21:
            case DHT22:
              _humidity = (uint16_t(data[0] << 8) | data[1]);
              _celsius = (uint16_t((data[2] & 0x7F) << 8) | data[3]) * ((data[2] & 0x80) ? -1 : 1);
              break;

            default: return false;
          }
          return true;
        }
      }
      return false;
    }

    uint16_t pulse(uint8_t pin, int state) {
      uint16_t cycle = micros();
      while (digitalRead(pin) == state);
      return micros() - cycle;
    }
};

#endif
>


thanks,
Helder Rodrigues

**Comment by offcircuit** [comment]
but I couldn't make macros() work on attiny13,

Helder Rodrigues

**Comment by Ehsan-Shahnazi** [comment]
https://github.com/offcircuit/SDHT/pull/1#issuecomment-519702705

Hi

I mean only the numerical value of temperature and humidity.
Only the size of the code and the correct amount of temperature and humidity were important to me.

**Comment by Ehsan-Shahnazi** [comment]
https://github.com/offcircuit/SDHT/pull/1#issuecomment-519707851

macros() or micro()

**Comment by Ehsan-Shahnazi** [comment]
hello.
why compiled code is more than 1 kb.( the .hex file is 3kb !!!)
i use above code (https://github.com/offcircuit/SDHT/pull/1#issuecomment-519702705)
in command line show :

"Sketch uses **900 bytes (**87%) of program storage space. Maximum is 1024 bytes.
Global variables use 4 bytes (6%) of dynamic memory, leaving 60 bytes for local variables. Maximum is 64 bytes."

so i cant uplode to attiny 13 with programmer ??

**Comment by Ehsan-Shahnazi** [comment]
> 
> 
> hello.
> why compiled code is more than 1 kb.( the .hex file is 3kb !!!)
> i use above code ([#1 (comment)](https://github.com/offcircuit/SDHT/pull/1#issuecomment-519702705))
> in command line show :
> 
> "Sketch uses **900 bytes (**87%) of program storage space. Maximum is 1024 bytes.
> Global variables use 4 bytes (6%) of dynamic memory, leaving 60 bytes for local variables. Maximum is 64 bytes."
> 
> so i cant uplode to attiny 13 with programmer ??

**dont any problem...i can write program to ATtiny13.**

**Comment by Ehsan-Shahnazi** [comment]
Hi
After write program to attiny13, outpot dont work.!!
But on arduino uno its ok.

Where do you think the problem is?

**Pull request closed without merging**
